import os
import subprocess
import tempfile
import io

TECTONIC_BIN = os.path.join(os.path.dirname(__file__), "bin", "tectonic.exe")

def compile_latex_to_pdf(latex_source: str) -> bytes:
    """Compiles LaTeX source to PDF using tectonic."""
    if not os.path.exists(TECTONIC_BIN):
        raise FileNotFoundError(f"Tectonic binary not found at {TECTONIC_BIN}")
        
    with tempfile.TemporaryDirectory() as temp_dir:
        tex_path = os.path.join(temp_dir, "resume.tex")
        with open(tex_path, "w", encoding="utf-8") as f:
            f.write(latex_source)
            
        try:
            result = subprocess.run(
                [TECTONIC_BIN, tex_path],
                cwd=temp_dir,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                check=True
            )
        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"Tectonic compilation failed:\n{e.stderr}\n{e.stdout}")
            
        pdf_path = os.path.join(temp_dir, "resume.pdf")
        if not os.path.exists(pdf_path):
            raise RuntimeError("PDF file was not generated by Tectonic.")
            
        with open(pdf_path, "rb") as f:
            return f.read()
